[project]
name = "stacksvestor"
description = "A token vesting and airdrop manager for Stacks blockchain"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
boot_contracts = []

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.stacksvestor]
path = "contracts/stacksvestor.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
